# Generated by Django 6.0 on 2026-01-04 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "trust_score",
                    models.IntegerField(
                        default=50, help_text="Score 0-100 based on regulatory history"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="scans/")),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("detected_medicine", models.CharField(max_length=255, null=True)),
                ("risk_level", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(db_index=True, max_length=255)),
                ("generic_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.manufacturer",
                    ),
                ),
            ],
        ),
    ]
